img:
  location: E:/SpringBootPicture/uploadPic
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smzdm?serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${img.location}
  mvc:
    static-path-pattern: /**

  velocity:
    suffix: .html
    toolbox-config-location: toolbox.xml
multipart:
  max-file-size: 1Mb
  max-request-size: 5Mb





#mybatis:
#  config-location:

#spring.velocity.suffix=.html
#放在主配置文件，修改velocity默认的模板后缀名

